game_name: "leduc_poker"
seed: 42
mode: "self_play"
algo: "ppo"

training:
  num_episodes: 200000
  eval_every: 5000
  save_path: "models/ppo/ppo_selfplay_final.pth"

agent:
  lr: 0.0003
  hidden_sizes: [256, 256]
  ppo_epochs: 10
  clip_param: 0.2
  gamma: 0.99